# Generated by Django 4.0.1 on 2022-01-11 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_polls_alter_choice_question_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 43, 42, 776861), verbose_name='date published'),
        ),
    ]
