# Generated by Django 4.0.1 on 2022-01-11 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_polls_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='polls',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 44, 6, 868457), verbose_name='date published'),
        ),
    ]
