# Generated by Django 4.0.1 on 2022-01-11 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_polls_pub_date_polls_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 16, 48, 13, 294876), verbose_name='date creation'),
        ),
    ]
