# Generated by Django 4.0.1 on 2022-01-12 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_subject_remove_polls_question_remove_polls_sujet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='sujet',
        ),
        migrations.AddField(
            model_name='polls',
            name='Question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='Sujet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 9, 19, 44, 651302), verbose_name='date creation'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
