# Generated by Django 4.0.1 on 2022-01-12 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_polls_sujet_polls_question_polls_sujet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 9, 22, 19, 837179), verbose_name='date creation'),
        ),
    ]
