# Generated by Django 4.0.1 on 2022-01-13 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_polls_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sujet', models.CharField(blank=True, max_length=200)),
                ('Question', models.CharField(blank=True, max_length=200, null=True)),
                ('option_1', models.CharField(blank=True, max_length=30, null=True)),
                ('option_2', models.CharField(blank=True, max_length=30, null=True)),
                ('option_3', models.CharField(blank=True, max_length=30, null=True)),
                ('option_4', models.CharField(blank=True, max_length=30, null=True)),
                ('option_1_count', models.IntegerField(default=0)),
                ('option_2_count', models.IntegerField(default=0)),
                ('option_3_count', models.IntegerField(default=0)),
                ('option_4_count', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2022, 1, 13, 21, 26, 9, 888890), verbose_name='date creation')),
            ],
        ),
        migrations.DeleteModel(
            name='Polls',
        ),
    ]
