# Generated by Django 4.0.1 on 2022-01-13 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_poll_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 22, 41, 43, 139351), verbose_name='date creation'),
        ),
    ]
