# Generated by Django 4.0.1 on 2022-01-16 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_poll_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='Sujet',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 39, 37, 696318), verbose_name='date creation'),
        ),
    ]
