# Generated by Django 4.0.1 on 2022-01-17 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_poll_sujet_alter_poll_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 51, 30, 475722), verbose_name='date creation'),
        ),
    ]
