# Generated by Django 4.0.1 on 2022-01-18 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_poll_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 10, 53, 35, 290256), verbose_name='date creation'),
        ),
    ]
