# Generated by Django 3.2.9 on 2022-01-25 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_poll_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 13, 49, 46, 260765), verbose_name='date creation'),
        ),
    ]
