# Generated by Django 3.2.9 on 2022-01-27 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20220127_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='creator',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 18, 35, 20, 673500, tzinfo=utc), verbose_name='date creation'),
        ),
    ]
