# Generated by Django 3.2.9 on 2022-01-30 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20220130_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 20, 10, 42, 4218, tzinfo=utc), verbose_name='date creation'),
        ),
    ]
