# Generated by Django 4.0.2 on 2022-02-01 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_poll_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 19, 54, 44, 917235, tzinfo=utc), verbose_name='date creation'),
        ),
    ]
