# Generated by Django 4.0.2 on 2022-02-10 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_poll_author_alter_poll_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 12, 3, 49, 446766, tzinfo=utc), verbose_name='date creation'),
        ),
    ]
